"""
IBC Setup Script for VolatilityHunter
======================================
Downloads and configures IBC (Interactive Brokers Controller) for
fully headless, unattended TWS / IB Gateway auto-login.

IBC is the official open-source solution endorsed by IBKR for automated login.
GitHub: https://github.com/IbcAlpha/IBC

Run once: python scripts/setup_ibc.py
After setup, auto_tws_manager.py will use IBC for all subsequent launches.

ASCII output only - Task Scheduler compatible.
"""

import os
import sys
import zipfile
import shutil
import urllib.request
import traceback
from pathlib import Path
from dotenv import load_dotenv

ROOT = Path(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
IBC_DIR = Path("C:\\IBC")
IBC_VERSION = "3.23.0"
IBC_ZIP_URL = f"https://github.com/IbcAlpha/IBC/releases/download/{IBC_VERSION}/IBCWin-{IBC_VERSION}.zip"
IBC_ZIP_PATH = IBC_DIR / f"IBCWin-{IBC_VERSION}.zip"

load_dotenv(ROOT / ".env")
IBKR_USER = os.getenv("IBKR_USER_NAME", "")
IBKR_PASS = os.getenv("IBKR_PASSWORD", "")


def print_step(msg):
    print(f"\n[STEP] {msg}")


def print_ok(msg):
    print(f"  [OK] {msg}")


def print_fail(msg):
    print(f"  [FAIL] {msg}")


def download_ibc():
    print_step(f"Downloading IBC v{IBC_VERSION}...")
    IBC_DIR.mkdir(parents=True, exist_ok=True)
    try:
        print(f"  URL : {IBC_ZIP_URL}")
        print(f"  Dest: {IBC_ZIP_PATH}")
        urllib.request.urlretrieve(IBC_ZIP_URL, IBC_ZIP_PATH)
        print_ok("Download complete.")
        return True
    except Exception as e:
        print_fail(f"Download failed: {e}")
        print("  --> Download manually from:")
        print(f"      https://github.com/IbcAlpha/IBC/releases/tag/{IBC_VERSION}")
        print(f"      and extract to {IBC_DIR}")
        return False


def extract_ibc():
    print_step("Extracting IBC...")
    try:
        with zipfile.ZipFile(IBC_ZIP_PATH, 'r') as z:
            z.extractall(IBC_DIR)
        print_ok(f"Extracted to {IBC_DIR}")
        # Clean up zip
        IBC_ZIP_PATH.unlink(missing_ok=True)
        return True
    except Exception as e:
        print_fail(f"Extract failed: {e}")
        traceback.print_exc()
        return False


def write_ibc_config():
    """
    Write IBC config.ini with credentials loaded from .env.
    This file tells IBC your IBKR username/password and TWS settings.
    """
    print_step("Writing IBC config.ini...")

    if not IBKR_USER or not IBKR_PASS:
        print_fail("IBKR_USER_NAME or IBKR_PASSWORD not found in .env")
        return False

    # Detect IB Gateway path - use raw string to preserve backslashes
    gateway_path = r"D:\TWS\ibgateway"
    if not Path(gateway_path).exists():
        gateway_path = r"C:\Jts"

    # NOTE: TradingMode is NOT a config.ini key in IBC 3.18+
    # It must be passed as the 3rd command-line argument to IbcGateway
    config_content = (
        "# IBC Configuration for VolatilityHunter\n"
        "# Auto-generated by scripts/setup_ibc.py\n"
        "# DO NOT commit this file - credentials stored here\n"
        "\n"
        "[IBC]\n"
        f"IbLoginId={IBKR_USER}\n"
        f"IbPassword={IBKR_PASS}\n"
        f"IbDir={gateway_path}\n"
        "StoreSettingsOnServer=no\n"
        "MinimizeMainWindow=yes\n"
        "ExistingSessionDetectedAction=primary\n"
        "AcceptIncomingConnectionAction=accept\n"
        "ShowAllTrades=no\n"
        "FIX=no\n"
        "IbAutoClosedown=no\n"
        "ClosedownAt=\n"
        "AllowBlindTrading=yes\n"
        "DismissPasswordExpiryWarning=yes\n"
        "DismissNSEComplianceNotice=yes\n"
        "AcceptBidAskLastSizeDisplayUpdateNotification=accept\n"
        "LogComponents=never\n"
    )

    config_path = IBC_DIR / "config.ini"
    try:
        with open(config_path, 'w') as f:
            f.write(config_content)
        print_ok(f"Config written to {config_path}")
        return True
    except Exception as e:
        print_fail(f"Failed to write config: {e}")
        traceback.print_exc()
        return False


ZULU_JRE_DIR  = Path(os.environ.get('USERPROFILE', 'C:\\Users\\Public')) / "zulu-jre17"
ZULU_JRE_URL  = "https://cdn.azul.com/zulu/bin/zulu17.64.17-ca-jre17.0.18-win_x64.zip"
ZULU_JRE_ZIP  = ZULU_JRE_DIR.parent / "zulu17-jre.zip"


def _java_version(java_exe: str) -> int:
    """Return major Java version (e.g. 17) or 0 on failure."""
    import subprocess as _sp
    try:
        out = _sp.check_output(
            [java_exe, "-version"], stderr=_sp.STDOUT, timeout=5
        ).decode(errors='ignore')
        # 'version "17.0.x"' or 'version "1.8.0_xx"'
        import re
        m = re.search(r'version "(\d+)(?:\.(\d+))?', out)
        if m:
            major = int(m.group(1))
            if major == 1:          # old-style 1.8 -> 8
                major = int(m.group(2) or 0)
            return major
    except Exception:
        pass
    return 0


def download_zulu_jre():
    """Download and extract Azul Zulu JRE 17 to C:\\zulu-jre17."""
    print_step("Downloading Azul Zulu JRE 17 (required by IB Gateway)...")
    ZULU_JRE_DIR.parent.mkdir(parents=True, exist_ok=True)
    try:
        print(f"  URL : {ZULU_JRE_URL}")
        print(f"  Dest: {ZULU_JRE_ZIP}")
        urllib.request.urlretrieve(ZULU_JRE_URL, ZULU_JRE_ZIP)
        print_ok("Download complete - extracting...")
        import zipfile
        with zipfile.ZipFile(ZULU_JRE_ZIP, 'r') as z:
            # Zip has a top-level folder like zulu17.xx.xx-ca-jre17.x.x-win_x64/
            top = z.namelist()[0].split('/')[0]
            z.extractall(ZULU_JRE_DIR.parent)
        extracted = ZULU_JRE_DIR.parent / top
        if extracted.exists() and extracted != ZULU_JRE_DIR:
            import shutil
            if ZULU_JRE_DIR.exists():
                shutil.rmtree(ZULU_JRE_DIR)
            extracted.rename(ZULU_JRE_DIR)
        ZULU_JRE_ZIP.unlink(missing_ok=True)
        java = ZULU_JRE_DIR / "bin" / "javaw.exe"
        if java.exists():
            print_ok(f"Zulu JRE 17 installed at {java}")
            return str(java)
        else:
            print_fail(f"Extract succeeded but javaw.exe not found at {java}")
            return ""
    except Exception as e:
        print_fail(f"Zulu JRE download failed: {e}")
        traceback.print_exc()
        return ""


def find_java() -> str:
    """
    Discover javaw.exe >= Java 17 on this machine.
    Checks known locations first; if none qualify, downloads Zulu JRE 17.
    Returns full path or empty string if not found.
    """
    import glob as _glob
    gateway_path = r"D:\TWS\ibgateway"
    if not Path(gateway_path).exists():
        gateway_path = r"C:\Jts"

    candidates = [
        str(ZULU_JRE_DIR / "bin" / "javaw.exe"),      # previously downloaded
        str(Path(gateway_path) / "jre" / "bin" / "javaw.exe"),
        r"C:\Program Files\Zulu\zulu-17\bin\javaw.exe",
        r"C:\Program Files\Zulu\zulu-21\bin\javaw.exe",
        r"C:\Program Files\Eclipse Adoptium\jre-17\bin\javaw.exe",
        r"C:\Program Files\Microsoft\jdk-17\bin\javaw.exe",
    ]
    # add any javaw.exe found via glob
    hits = _glob.glob(r"C:\Program Files\**\javaw.exe", recursive=True)
    hits += _glob.glob(r"C:\Program Files (x86)\**\javaw.exe", recursive=True)
    candidates += hits

    for c in candidates:
        p = Path(c)
        if p.is_file() and _java_version(str(p)) >= 17:
            return str(p)

    # Nothing on this machine is Java 17+ - download Zulu 17 automatically
    print_fail("No Java 17+ found on this machine - downloading Zulu JRE 17...")
    return download_zulu_jre()


def write_start_script():
    """
    Write StartGateway.bat - the script that launches IB Gateway via IBC.
    auto_tws_manager.py will call this instead of launching ibgateway.exe directly.
    """
    print_step("Writing StartGateway.bat...")

    java_path = find_java()
    if java_path:
        print_ok(f"Java found: {java_path}")
    else:
        print_fail("Java not found - StartGateway.bat will use bare 'javaw' (may fail if not on PATH)")
        java_path = "javaw"

    gateway_path = "D:\\TWS\\ibgateway"
    if not Path(gateway_path).exists():
        gateway_path = "C:\\Jts"

    # TradingMode is the 3rd positional arg in IBC 3.18+ (live or paper)
    trading_mode = "live"

    log_path = str(ROOT / "logs" / "ibc_gateway.log")

    bat_content = (
        "@echo off\r\n"
        "REM IBC Auto-Start Script for IB Gateway\r\n"
        "REM Generated by scripts/setup_ibc.py\r\n"
        "\r\n"
        f'set IBC_PATH=C:\\IBC\r\n'
        f'set TWS_PATH={gateway_path}\r\n'
        f'set "JAVA_PATH={java_path}"\r\n'
        f'set CONFIG=%IBC_PATH%\\config.ini\r\n'
        f'set "LOG_PATH={log_path}"\r\n'
        "\r\n"
        'echo Starting IB Gateway via IBC at %DATE% %TIME% >> "%LOG_PATH%"\r\n'
        "\r\n"
        '"%JAVA_PATH%" -cp "%IBC_PATH%\\IBC.jar;%TWS_PATH%\\jars\\*" '
        f'ibcalpha.ibc.IbcGateway "%CONFIG%" "%TWS_PATH%" {trading_mode}'
        ' >> "%LOG_PATH%" 2>&1\r\n'
        "\r\n"
        'echo IBC process exited at %DATE% %TIME% >> "%LOG_PATH%"\r\n'
    )

    bat_path = IBC_DIR / "StartGateway.bat"
    try:
        with open(bat_path, 'w') as f:
            f.write(bat_content)
        print_ok(f"StartGateway.bat written to {bat_path}")
        return True
    except Exception as e:
        print_fail(f"Failed to write StartGateway.bat: {e}")
        traceback.print_exc()
        return False


def verify_setup():
    print_step("Verifying IBC setup...")
    ok = True

    checks = [
        (IBC_DIR / "IBC.jar",          "IBC.jar"),
        (IBC_DIR / "config.ini",       "config.ini"),
        (IBC_DIR / "StartGateway.bat", "StartGateway.bat"),
    ]
    for path, name in checks:
        if path.exists():
            print_ok(f"{name} found at {path}")
        else:
            print_fail(f"{name} NOT found at {path}")
            ok = False

    return ok


def main():
    print("=" * 60)
    print("IBC SETUP FOR VOLATILITYHUNTER")
    print("Headless IB Gateway auto-login configuration")
    print("=" * 60)

    if not IBKR_USER or not IBKR_PASS:
        print("\n[FAIL] IBKR_USER_NAME and IBKR_PASSWORD must be set in .env")
        sys.exit(1)

    print(f"\n  IBKR Username : {IBKR_USER}")
    print(f"  IBC Install   : {IBC_DIR}")
    print(f"  IBC Version   : {IBC_VERSION}")

    # If IBC already extracted, skip download
    ibc_jar = IBC_DIR / "IBC.jar"
    if ibc_jar.exists():
        print("\n  IBC.jar already exists - skipping download.")
    else:
        if not download_ibc():
            print("\n  Manual fallback: download IBCWindows zip, extract to C:\\IBC")
            # Still write config and bat even if download failed
        else:
            extract_ibc()

    write_ibc_config()
    write_start_script()

    ok = verify_setup()
    print()
    print("=" * 60)
    if ok:
        print("IBC SETUP COMPLETE")
        print("IB Gateway will now auto-login when auto_tws_manager.py runs.")
        print(f"Start script: {IBC_DIR}\\StartGateway.bat")
    else:
        print("SETUP INCOMPLETE - Some files missing.")
        print(f"Manually extract IBC zip to {IBC_DIR} and re-run.")
    print("=" * 60)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
