"""
IBC Setup Script for VolatilityHunter
======================================
Downloads and configures IBC (Interactive Brokers Controller) for
fully headless, unattended TWS / IB Gateway auto-login.

IBC is the official open-source solution endorsed by IBKR for automated login.
GitHub: https://github.com/IbcAlpha/IBC

Run once: python scripts/setup_ibc.py
After setup, auto_tws_manager.py will use IBC for all subsequent launches.

ASCII output only - Task Scheduler compatible.
"""

import os
import sys
import zipfile
import shutil
import urllib.request
import traceback
from pathlib import Path
from dotenv import load_dotenv

ROOT = Path(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
IBC_DIR = Path("C:\\IBC")
IBC_VERSION = "3.23.0"
IBC_ZIP_URL = f"https://github.com/IbcAlpha/IBC/releases/download/{IBC_VERSION}/IBCWin-{IBC_VERSION}.zip"
IBC_ZIP_PATH = IBC_DIR / f"IBCWin-{IBC_VERSION}.zip"

load_dotenv(ROOT / ".env")
IBKR_USER = os.getenv("IBKR_USER_NAME", "")
IBKR_PASS = os.getenv("IBKR_PASSWORD", "")


def print_step(msg):
    print(f"\n[STEP] {msg}")


def print_ok(msg):
    print(f"  [OK] {msg}")


def print_fail(msg):
    print(f"  [FAIL] {msg}")


def download_ibc():
    print_step(f"Downloading IBC v{IBC_VERSION}...")
    IBC_DIR.mkdir(parents=True, exist_ok=True)
    try:
        print(f"  URL : {IBC_ZIP_URL}")
        print(f"  Dest: {IBC_ZIP_PATH}")
        urllib.request.urlretrieve(IBC_ZIP_URL, IBC_ZIP_PATH)
        print_ok("Download complete.")
        return True
    except Exception as e:
        print_fail(f"Download failed: {e}")
        print("  --> Download manually from:")
        print(f"      https://github.com/IbcAlpha/IBC/releases/tag/{IBC_VERSION}")
        print(f"      and extract to {IBC_DIR}")
        return False


def extract_ibc():
    print_step("Extracting IBC...")
    try:
        with zipfile.ZipFile(IBC_ZIP_PATH, 'r') as z:
            z.extractall(IBC_DIR)
        print_ok(f"Extracted to {IBC_DIR}")
        # Clean up zip
        IBC_ZIP_PATH.unlink(missing_ok=True)
        return True
    except Exception as e:
        print_fail(f"Extract failed: {e}")
        traceback.print_exc()
        return False


def write_ibc_config():
    """
    Write IBC config.ini with credentials loaded from .env.
    This file tells IBC your IBKR username/password and TWS settings.
    """
    print_step("Writing IBC config.ini...")

    if not IBKR_USER or not IBKR_PASS:
        print_fail("IBKR_USER_NAME or IBKR_PASSWORD not found in .env")
        return False

    # Detect IB Gateway path
    gateway_path = "D:\\TWS\\ibgateway"
    if not Path(gateway_path).exists():
        gateway_path = "C:\\Jts"

    config_content = f"""# IBC Configuration for VolatilityHunter
# Auto-generated by scripts/setup_ibc.py
# DO NOT commit this file - credentials are stored here

[IBC]
IbLoginId={IBKR_USER}
IbPassword={IBKR_PASS}
TradingMode=live
IbDir={gateway_path}
StoreSettingsOnServer=no
MinimizeMainWindow=yes
ExistingSessionDetectedAction=primary
AcceptIncomingConnectionAction=accept
ShowAllTrades=no
FIX=no
IbAutoClosedown=no
ClosedownAt=
AllowBlindTrading=yes
DismissPasswordExpiryWarning=yes
DismissNSEComplianceNotice=yes
AcceptBidAskLastSizeDisplayUpdateNotification=accept
LogComponents=never
"""

    config_path = IBC_DIR / "config.ini"
    try:
        with open(config_path, 'w') as f:
            f.write(config_content)
        print_ok(f"Config written to {config_path}")
        return True
    except Exception as e:
        print_fail(f"Failed to write config: {e}")
        traceback.print_exc()
        return False


def write_start_script():
    """
    Write StartGateway.bat - the script that launches IB Gateway via IBC.
    auto_tws_manager.py will call this instead of launching ibgateway.exe directly.
    """
    print_step("Writing StartGateway.bat...")

    # Find Java - IBC needs Java from the IB Gateway installation
    java_path = "D:\\TWS\\ibgateway\\jre\\bin\\java.exe"
    if not Path(java_path).exists():
        java_path = "C:\\Jts\\jre\\bin\\java.exe"
    if not Path(java_path).exists():
        java_path = "java"  # fallback to system Java

    gateway_path = "D:\\TWS\\ibgateway"
    if not Path(gateway_path).exists():
        gateway_path = "C:\\Jts"

    bat_content = f"""@echo off
REM IBC Auto-Start Script for IB Gateway
REM Generated by scripts/setup_ibc.py

set IBC_PATH=C:\\IBC
set TWS_PATH={gateway_path}
set JAVA_PATH={java_path}
set CONFIG=%IBC_PATH%\\config.ini
set LOG_PATH={str(ROOT)}\\logs\\ibc_gateway.log

echo Starting IB Gateway via IBC at %DATE% %TIME% >> "%LOG_PATH%"

"{java_path}" -cp "%IBC_PATH%\\IBC.jar;%TWS_PATH%\\jars\\*" ibcalpha.ibc.IbcGateway ^
    "%CONFIG%" ^
    "%TWS_PATH%" ^
    >> "%LOG_PATH%" 2>&1

echo IBC process exited at %DATE% %TIME% >> "%LOG_PATH%"
"""

    bat_path = IBC_DIR / "StartGateway.bat"
    try:
        with open(bat_path, 'w') as f:
            f.write(bat_content)
        print_ok(f"StartGateway.bat written to {bat_path}")
        return True
    except Exception as e:
        print_fail(f"Failed to write StartGateway.bat: {e}")
        traceback.print_exc()
        return False


def verify_setup():
    print_step("Verifying IBC setup...")
    ok = True

    checks = [
        (IBC_DIR / "IBC.jar",          "IBC.jar"),
        (IBC_DIR / "config.ini",       "config.ini"),
        (IBC_DIR / "StartGateway.bat", "StartGateway.bat"),
    ]
    for path, name in checks:
        if path.exists():
            print_ok(f"{name} found at {path}")
        else:
            print_fail(f"{name} NOT found at {path}")
            ok = False

    return ok


def main():
    print("=" * 60)
    print("IBC SETUP FOR VOLATILITYHUNTER")
    print("Headless IB Gateway auto-login configuration")
    print("=" * 60)

    if not IBKR_USER or not IBKR_PASS:
        print("\n[FAIL] IBKR_USER_NAME and IBKR_PASSWORD must be set in .env")
        sys.exit(1)

    print(f"\n  IBKR Username : {IBKR_USER}")
    print(f"  IBC Install   : {IBC_DIR}")
    print(f"  IBC Version   : {IBC_VERSION}")

    # If IBC already extracted, skip download
    ibc_jar = IBC_DIR / "IBC.jar"
    if ibc_jar.exists():
        print("\n  IBC.jar already exists - skipping download.")
    else:
        if not download_ibc():
            print("\n  Manual fallback: download IBCWindows zip, extract to C:\\IBC")
            # Still write config and bat even if download failed
        else:
            extract_ibc()

    write_ibc_config()
    write_start_script()

    ok = verify_setup()
    print()
    print("=" * 60)
    if ok:
        print("IBC SETUP COMPLETE")
        print("IB Gateway will now auto-login when auto_tws_manager.py runs.")
        print(f"Start script: {IBC_DIR}\\StartGateway.bat")
    else:
        print("SETUP INCOMPLETE - Some files missing.")
        print(f"Manually extract IBC zip to {IBC_DIR} and re-run.")
    print("=" * 60)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
